/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:40e2865b-c5ee-46dc-abaa-5cf6e25d2895",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_KBxr6Cc3t",
    "aws_user_pools_web_client_id": "2msrdfos7em3jehkrlvojlcatn",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "pep8109e785a-dev",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
